// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Rocksmith2014.DD.Model
{
    public class ModelInput
    {
        [ColumnName("key"), LoadColumn(0)]
        public string Key { get; set; }


        [ColumnName("arrName"), LoadColumn(1)]
        public string ArrName { get; set; }


        [ColumnName("path"), LoadColumn(2)]
        public float Path { get; set; }


        [ColumnName("phrase"), LoadColumn(3)]
        public string Phrase { get; set; }


        [ColumnName("levels"), LoadColumn(4)]
        public float Levels { get; set; }


        [ColumnName("uniqueLevels"), LoadColumn(5)]
        public float UniqueLevels { get; set; }


        [ColumnName("lengthMs"), LoadColumn(6)]
        public float LengthMs { get; set; }


        [ColumnName("lengthBeats"), LoadColumn(7)]
        public float LengthBeats { get; set; }


        [ColumnName("tempo"), LoadColumn(8)]
        public float Tempo { get; set; }


        [ColumnName("notes"), LoadColumn(9)]
        public float Notes { get; set; }


        [ColumnName("repeatedNotes"), LoadColumn(10)]
        public float RepeatedNotes { get; set; }


        [ColumnName("chords"), LoadColumn(11)]
        public float Chords { get; set; }


        [ColumnName("repeatedChords"), LoadColumn(12)]
        public float RepeatedChords { get; set; }


        [ColumnName("techCount"), LoadColumn(13)]
        public float TechCount { get; set; }


        [ColumnName("palmMutes"), LoadColumn(14)]
        public float PalmMutes { get; set; }


        [ColumnName("bends"), LoadColumn(15)]
        public float Bends { get; set; }


        [ColumnName("harmonics"), LoadColumn(16)]
        public float Harmonics { get; set; }


        [ColumnName("pharmonics"), LoadColumn(17)]
        public float Pharmonics { get; set; }


        [ColumnName("taps"), LoadColumn(18)]
        public float Taps { get; set; }


        [ColumnName("tremolos"), LoadColumn(19)]
        public float Tremolos { get; set; }


        [ColumnName("vibratos"), LoadColumn(20)]
        public float Vibratos { get; set; }


        [ColumnName("slides"), LoadColumn(21)]
        public float Slides { get; set; }


        [ColumnName("unpSlides"), LoadColumn(22)]
        public float UnpSlides { get; set; }


        [ColumnName("ignored"), LoadColumn(23)]
        public float Ignored { get; set; }


        [ColumnName("anchors"), LoadColumn(24)]
        public float Anchors { get; set; }


        [ColumnName("maxChordStrings"), LoadColumn(25)]
        public float MaxChordStrings { get; set; }


        [ColumnName("solo"), LoadColumn(26)]
        public string Solo { get; set; }


    }
}
